NUM_FEATURES    = 1024
NUM_SAMPLES     = 5000
NUM_TRAINING    = 4500
NUM_TESTING     = 500
STEP_SIZE       = 60000
NUM_EPOCHS      = 5
DATA_SET_SIZE   = NUM_FEATURES * NUM_SAMPLES

# For accelerator. May not be needed for LLVM JIT compilation
VFTYPE_WIDTH    = 512
VDTYPE_WIDTH    = 512

FTYPE_TWIDTH    = 32
FTYPE_IWIDTH    = 13

F_VECTOR_SIZE   = VFTYPE_WIDTH / FTYPE_TWIDTH

DTYPE_TWIDTH    = 16
DTYPE_IWIDTH    = 4

D_VECTOR_SIZE   = VDTYPE_WIDTH / DTYPE_TWIDTH

LTYPE_WIDTH     = 8
VLTYPE_WIDTH    = 32

L_VECTOR_SIZE   = VLTYPE_WIDTH / LTYPE_WIDTH

LUTOUT_TWIDTH   = 12
LUTOUT_IWIDTH   = 2
LUTIN_TWIDTH    = 12
LUTIN_IWIDTH    = 4

PAR_FACTOR      = 32
